language: go
go:
  - "1.13.x"
dist: trusty
addons:
  sonarcloud:
    organization: "jasonpep-github"
    token:
      secure: $SONAR_TOKEN
script:
  - make test
  - sonar-scanner
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - jasonsuler@gmail.com