language: go
go:
  - "1.x"
  - "1.10"
  - "1.10.x"
  - "1.11"
  - "1.11.x"
  - "1.13.x"
  - master
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
      - jasonsuler@gmail.com